[deps]
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"

[sources]
BonitoBook = {url = "https://github.com/SimonDanisch/BonitoBook.jl"}
