# keymap.toml
#[[mgr.prepend_keymap]]
#on   = "T"
#run  = "plugin toggle-pane min-preview"
#desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
