name: Dotfiles Installation

on:
  push:
  schedule:
    - cron: "0 17 * * 4" # Every Thursday 5:00PM

concurrency:
  group: dotfiles-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]

    steps:
      - name: Download and install available system updates
        # Step disabled since it also tries to update macOS itself and there seems no way to disable this
        if: ${{ false && startsWith(matrix.os, 'macos') }}
        run: sudo softwareupdate -i -a

      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Install using Makefile
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            make macos-ci
          else
            sudo make linux
          fi

      - name: Load & verify runcom setup
        run: source $HOME/.bash_profile

      - name: Install test dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq

      - name: Run tests
        run: make test
